"""Коды ошибок FSM (нормативные имена для last_error и диагностики)."""

from __future__ import annotations


class FsmErrorCodes:
    """Набор строковых констант ошибок платформы FSM. Используются в last_error экземпляров и логах."""

    MISSING_PROCESS_NAME = "MISSING_PROCESS_NAME"
    UNKNOWN_PROCESS = "UNKNOWN_PROCESS"
    INVALID_STATE_RETURNED = "INVALID_STATE_RETURNED"
    CONTEXT_BUILD_FAILED = "CONTEXT_BUILD_FAILED"
    MISSING_ENTITY_TYPE = "MISSING_ENTITY_TYPE"
    MISSING_ENTITY_ID = "MISSING_ENTITY_ID"
    ENTITY_STATE_NOT_FOUND = "ENTITY_STATE_NOT_FOUND"
    NO_CANDIDATE_TRANSITIONS = "NO_CANDIDATE_TRANSITIONS"
    AMBIGUOUS_TRANSITION = "AMBIGUOUS_TRANSITION"
    UNKNOWN_GUARD = "UNKNOWN_GUARD"
    NO_GUARD_MATCHED = "NO_GUARD_MATCHED"
    UNKNOWN_EFFECT = "UNKNOWN_EFFECT"
    EFFECT_FAILED = "EFFECT_FAILED"
    STATE_MISMATCH = "STATE_MISMATCH"
    APPLY_FAILED = "APPLY_FAILED"
